spring:
   profiles:
      active: ${app.version}
      
   thymeleaf:
      cache: false
      prefix: classpath:/templates/
   resources:
      static-locations: classpath:/static/

server:
  port: 8100

---
spring:
   profiles: windows
   
   datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://localhost;databaseName=TacoDB
      username: sa
      password: kramer
   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
           dialect: org.hibernate.dialect.SQLServer2012Dialect
      show-sql: true
      
logging:
   file: C:\Users\noratt\Documents\Logging\taco-cloud\tacoCloud.log
   level:
      ROOT: INFO
      
---
spring:
   profiles: mac
   
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password:
   
   h2:
      console:
         enabled: true
         path: /h2-console
   