project:
  base-dir: file:///P:/git/taco-cloud
server:
  port: 8100
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: kramer
    url: jdbc:sqlserver://localhost;databaseName=TacoDB
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
  thymeleaf:
    cache: false
    prefix: ${project.base-dir}/src/main/resources/templates/
  resources:
    static-locations: ${project.base-dir}/src/main/resources/static/