project:
  base-dir: file:///P:/git/taco-cloud
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  thymeleaf:
    cache: false
    prefix: ${project.base-dir}/src/main/resources/templates/
